---
- name: restart containerd
  service:
    name: containerd
    state: restarted

- name: restart apparmor
  ## Can't start apparmor service in molecule sles15 docker image
  tags: notest
  service:
    name: apparmor
    state: restarted
